services:
    Aligent\ShippingEstimatorBundle\Factory\ShippingEstimatorShippingContextFactory:
        public: true
        arguments:
            - '@oro_config.global'
            - '@Aligent\ShippingEstimatorBundle\Converter\ShoppingListShippingLineItemConverter'
            - '@oro_shipping.context.builder_factory_basic'

    Aligent\ShippingEstimatorBundle\Layout\DataProvider\ShippingEstimatorFormProvider:
        public: true
        arguments:
            - '@form.factory'
            - '@router'
        tags:
            - { name: layout.data_provider, alias: shipping_estimator }

    Aligent\ShippingEstimatorBundle\Form\Type\ShippingEstimatorType:
        arguments:
            - '@Aligent\ShippingEstimatorBundle\Form\EventListener\CountryAndRegionSubscriber'
        tags:
            - { name: form.type, alias: shippingEstimator }

    Aligent\ShippingEstimatorBundle\Converter\ShoppingListShippingLineItemConverter:
        arguments:
            - '@oro_shipping.context.line_item_collection_factory.set_shipping_options_if_null'
            - '@oro_shipping.line_item.factory_basic'

    Aligent\ShippingEstimatorBundle\Form\EventListener\CountryAndRegionSubscriber:
        arguments:
            - '@doctrine'
            - '@form.factory'
