services:
    Aligent\ShippingEstimatorBundle\Factory\ShippingEstimatorShippingContextFactory:
        public: true
        arguments:
            - '@oro_config.global'
            - '@oro_order.shipping_line_item.converter_basic'
            - '@oro_shipping.context.builder_factory_basic'

    Aligent\ShippingEstimatorBundle\Layout\DataProvider\ShippingEstimatorFormProvider:
        public: true
        arguments:
            - '@form.factory'
            - '@router'
        tags:
            - { name: layout.data_provider, alias: shipping_estimator }

    Aligent\ShippingEstimatorBundle\Form\Type\ShippingEstimatorType:
        arguments:
            - '@Aligent\ShippingEstimatorBundle\Form\EventListener\CountryAndRegionSubscriber'
        tags:
            - { name: form.type, alias: shippingEstimator }

    Aligent\ShippingEstimatorBundle\Form\EventListener\CountryAndRegionSubscriber:
        arguments:
            - '@doctrine'
            - '@form.factory'
