features:
    aligent_shipping_estimator:
        label: aligent.shipping.estimator.system_configuration.fields.is_enabled.label
        description: aligent.shipping.estimator.system_configuration.fields.is_enabled.tooltip
        toggle: aligent_shipping_estimator.is_enabled
        strategy: affirmative
